# Generated by Django 5.2.15 on 2026-06-29 01:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: INF-001, SW-001', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INF', 'Información y datos'), ('SW', 'Software y aplicaciones'), ('HW', 'Hardware e infraestructura'), ('SRV', 'Servicios digitales'), ('PER', 'Personas y roles críticos'), ('IDN', 'Identidad y acceso'), ('RED', 'Red y comunicaciones'), ('DOC', 'Documentación y conocimiento'), ('REP', 'Reputación digital'), ('TER', 'Terceros y proveedores')], max_length=5)),
                ('descripcion', models.TextField(blank=True)),
                ('proceso_asociado', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('propietario', models.CharField(blank=True, max_length=150)),
                ('custodio_tecnico', models.CharField(blank=True, max_length=150)),
                ('usuarios_principales', models.CharField(blank=True, max_length=300)),
                ('dependencias', models.TextField(blank=True, help_text='Otros activos de los que depende')),
                ('confidencialidad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('integridad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('disponibilidad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('valor_economico_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('EXTERNA', 'Amenaza externa'), ('INTERNA', 'Amenaza interna'), ('PROCESO', 'Amenaza de proceso y entorno')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('es_generica', models.BooleanField(default=False, help_text='Si viene del catálogo base de la metodología (no editable por todas las orgs)')),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Catálogo de Amenazas',
                'ordering': ['origen', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoVulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('TECNOLOGICA', 'Tecnológica'), ('ORGANIZACIONAL', 'Organizacional'), ('PROCESOS', 'De procesos'), ('TERCEROS', 'De terceros')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('es_generica', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Catálogo de Vulnerabilidades',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('PYME', 'Pequeña y Mediana Empresa'), ('SALUD', 'Hospital / Clínica / Sector Salud'), ('EDUCACION', 'Universidad / Institución Educativa'), ('INDUSTRIAL', 'Planta Industrial / Manufactura'), ('FINANCIERO', 'Entidad Financiera / Cooperativa'), ('GOBIERNO', 'Organismo Gubernamental / Municipio'), ('TECNOLOGIA', 'Empresa de Tecnología / Startup'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Procesos de negocio críticos, contexto general')),
                ('apetito_riesgo', models.CharField(choices=[('AVERSO', 'Averso al riesgo (umbrales bajos)'), ('MODERADO', 'Moderado'), ('TOLERANTE', 'Tolerante al riesgo (umbrales altos)')], default='MODERADO', max_length=20)),
                ('normativas_aplicables', models.CharField(blank=True, help_text='Ej: LOPDP, PCI-DSS, regulaciones sectoriales', max_length=300)),
                ('umbral_muy_bajo', models.DecimalField(decimal_places=2, default=1000, max_digits=14)),
                ('umbral_bajo', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('umbral_medio', models.DecimalField(decimal_places=2, default=50000, max_digits=14)),
                ('umbral_alto', models.DecimalField(decimal_places=2, default=200000, max_digits=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ControlExistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ACCESO', 'Control de acceso'), ('DATOS', 'Protección de datos'), ('CONTINUIDAD', 'Continuidad'), ('MONITOREO', 'Monitoreo'), ('VULNERABILIDADES', 'Gestión de vulnerabilidades'), ('CONCIENTIZACION', 'Concientización'), ('CUMPLIMIENTO', 'Cumplimiento LOPDP'), ('TERCEROS', 'Terceros')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('efectividad', models.IntegerField(choices=[(1, '1 - Baja'), (2, '2 - Media'), (3, '3 - Alta')], default=2, help_text='Qué tanto reduce la probabilidad/impacto del riesgo')),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='riskmanager.activo')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='riskmanager.organizacion')),
            ],
            options={
                'verbose_name': 'Control Existente',
                'verbose_name_plural': 'Controles Existentes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EscenarioRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: R-001', max_length=20)),
                ('descripcion_resultado', models.TextField(blank=True, help_text="Ej: 'Cifrado y pérdida de datos de clientes con impacto operativo y legal'")),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='riskmanager.activo')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='riskmanager.catalogoamenaza')),
                ('controles_mitigantes', models.ManyToManyField(blank=True, related_name='escenarios', to='riskmanager.controlexistente')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='riskmanager.catalogovulnerabilidad')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='riskmanager.organizacion')),
            ],
            options={
                'verbose_name': 'Escenario de Riesgo',
                'verbose_name_plural': 'Escenarios de Riesgo',
                'ordering': ['codigo'],
                'unique_together': {('organizacion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lef_min', models.DecimalField(decimal_places=4, help_text='Frecuencia anual mínima', max_digits=8)),
                ('lef_probable', models.DecimalField(decimal_places=4, help_text='Frecuencia anual más probable', max_digits=8)),
                ('lef_max', models.DecimalField(decimal_places=4, help_text='Frecuencia anual máxima', max_digits=8)),
                ('plm_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plm_probable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plm_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('slm_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('slm_probable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('slm_max', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='riskmanager.escenarioriesgo')),
            ],
            options={
                'verbose_name': 'Análisis de Riesgo',
                'verbose_name_plural': 'Análisis de Riesgos',
            },
        ),
        migrations.AddField(
            model_name='catalogovulnerabilidad',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='riskmanager.organizacion'),
        ),
        migrations.AddField(
            model_name='catalogoamenaza',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenazas', to='riskmanager.organizacion'),
        ),
        migrations.AddField(
            model_name='activo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='riskmanager.organizacion'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CISO', 'CISO / Responsable de Riesgos'), ('ANALISTA', 'Analista de Riesgos'), ('CONSULTA', 'Solo consulta')], default='ANALISTA', max_length=20)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='riskmanager.organizacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMontecarlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_iteraciones', models.IntegerField(default=10000)),
                ('distribucion', models.CharField(choices=[('PERT', 'PERT'), ('TRIANGULAR', 'Triangular')], default='PERT', max_length=20)),
                ('ale_media', models.DecimalField(decimal_places=2, help_text='Riesgo esperado (media)', max_digits=14)),
                ('ale_percentil_95', models.DecimalField(decimal_places=2, help_text='Peor caso razonable', max_digits=14)),
                ('ale_minimo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ale_maximo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('desviacion_estandar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('varianza', models.DecimalField(decimal_places=2, help_text='Indicador de incertidumbre', max_digits=18)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_montecarlo', to='riskmanager.analisisriesgo')),
            ],
            options={
                'verbose_name': 'Resultado de Simulación Montecarlo',
                'verbose_name_plural': 'Resultados de Simulación Montecarlo',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('EVITAR', 'Evitar'), ('ACEPTAR', 'Aceptar')], max_length=15)),
                ('descripcion_plan', models.TextField(help_text='Ej: instalar MFA, contratar seguro cibernético, etc.')),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('plazo_dias', models.IntegerField(blank=True, help_text='Plazo en días según nivel: 30 (Alto), 90 (Medio), etc.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('IMPLEMENTADO', 'Implementado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_implementacion', models.DateField(blank=True, null=True)),
                ('aprobado_por', models.CharField(blank=True, help_text='Requerido si estrategia = Aceptar (aprobación documentada, sección 7.1)', max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='riskmanager.escenarioriesgo')),
            ],
            options={
                'verbose_name': 'Tratamiento de Riesgo',
                'verbose_name_plural': 'Tratamientos de Riesgo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='activo',
            unique_together={('organizacion', 'codigo')},
        ),
    ]
