# Generated by Django 6.0.6 on 2026-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
